[features]
seeds = false
skip-lint = false
[programs.localnet]
amm = "GMvPvwCAmp8tassxdCcyENrc9cRvStvop5TYA7quhtBR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/resiquents/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
